# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.111.118.152:3306/mybatis
    username: mybatis
    password: password
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.van.mybatis.demo.entity
  type-handlers-package: cn.van.mybatis.demo.typehandler
logging:
  level:
    cn:
      van:
        mybatis:
          demo:
            mapper: debug